<?php
class DataProcessor {
    private $jsonFile = 'database_data.json';
    private $data = [];

    public function __construct() {
        // Read JSON file generated by Python script
        if (file_exists($this->jsonFile)) {
            $this->data = json_decode(file_get_contents($this->jsonFile), true);
        }
    }

    public function generateHTML() {
        $html = "<!DOCTYPE html>
        <html lang='en'>
        <head>
            <meta charset='UTF-8'>
            <title>Database Data Visualization</title>
            <style>
                table { border-collapse: collapse; width: 100%; }
                th, td { border: 1px solid black; padding: 8px; text-align: left; }
            </style>
        </head>
        <body>
            <h1>Database Data Overview</h1>
            <table>
                <thead>
                    <tr>
                        <th>Table Name</th>
                        <th>Timestamp</th>
                        <th>Workstation</th>
                        <th>Vision System</th>
                        <th>Old Status</th>
                        <th>Booth Last Occupied for</th>
                        <th>New Status</th>
                        <th>People Present in Camera</th>
                        <th>Frame Rate</th>
                        <th>Change of Presence - Total</th>
                        <th>Change of Presence p/Minute</th>
                    </tr>
                </thead>
                <tbody>";

        foreach ($this->data as $tableName => $tableData) {
            $html .= "<tr>";
            $html .= "<td>" . htmlspecialchars($tableName) . "</td>";
            
            foreach ($tableData as $pointValue) {
                $html .= "<td>" . htmlspecialchars($pointValue) . "</td>";
            }
            
            $html .= "</tr>";
        }

        $html .= "
                </tbody>
            </table>
        </body>
        </html>";

        file_put_contents('home.html', $html);
        return $html;
    }

    public function displayHTML() {
        echo $this->generateHTML();
    }
}

// Execute the data processing and HTML generation
$processor = new DataProcessor();
$processor->displayHTML();
?>